name: Firefox Web Extension Release
on:
  push:
    branches:
      - master
jobs:
  publish-firefox:
    name: "Build and sign Firefox Web Ext"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: "Get Version"
        run: echo "VERSION=$(jq -r '.version' manifest.json)" >> $GITHUB_ENV

      - name: "Echo Version"
        run: echo $VERSION

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: ./
          exclusions: '["skribbltypo.user.js", "userscript-gen.js"," patch.json", "/*extensions/*"]'

      - name: "web-ext sign"
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          channel: unlisted
          apiKey: ${{ secrets.MOZILLA_API_KEY }}
          apiSecret: ${{ secrets.MOZILLA_API_SECRET }}
          timeout: 900000

      - name: Archive signed XPI
        uses: actions/upload-artifact@v3
        with:
          name: typo-firefox-signed-release-${{env.VERSION}}
          path: ${{ steps.web-ext-sign.outputs.target }}

      - name: "Publish update to tobeh.host"
        env:
          FILE_PATH: ${{ steps.web-ext-sign.outputs.target }}
          VERSION: ${{env.VERSION}}
          AUTH: ${{ secrets.FF_UPDATE_AUTH }}
          SCRIPT_URL: ${{ secrets.FF_UPDATE_URL }}
        run: |
          curl -X POST -F "file=@$FILE_PATH" -F "version=$VERSION" -F "auth=$AUTH" $SCRIPT_URL

  publish-chrome:
    name: "Build and sign Chrome Web Ext"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: "Get Version"
        run: echo "VERSION=$(jq -r '.version' manifest.json)" >> $GITHUB_ENV

      - name: "Echo Version"
        run: echo $VERSION

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: typo-chrome-${{env.VERSION}}.zip
          exclusions: "*.git* *.xpi skribbltypo.user.js userscript-gen.js readme.md patch.json /*extensions/* *.web-extension-id .editorconfig .github/"

      - name: Archive signed XPI
        uses: actions/upload-artifact@v3
        with:
          name: typo-chrome-release-${{env.VERSION}}
          path: typo-chrome-release-${{env.VERSION}}.zip

  release:
    name: "Create a release and upload XPI"
    needs: [publish-firefox, publish-chrome]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Get Version"
        run: echo "VERSION=$(jq -r '.version' manifest.json)" >> $GITHUB_ENV

      - name: "Echo Version"
        run: echo $VERSION

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: skribbltypo-release-${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: Stable release of skribbl typo, version ${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload XPI
        id: upload_xpi
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ needs.publish-firefox.outputs.web-ext-sign.outputs.target }}
          asset_name: typo-firefox-signed-release-${{ env.VERSION }}.xpi
          asset_content_type: application/x-xpinstall

      - name: Download Chrome release
        uses: actions/download-artifact@v2
        with:
          name: typo-chrome-release-${{env.VERSION}}
          path: typo-chrome-release-${{env.VERSION}}.zip

      - name: Upload Zip
        id: upload_zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: typo-chrome-release-${{env.VERSION}}.zip
          asset_name: typo-chrome-release-${{env.VERSION}}.zip
          asset_content_type: application/zip
