name: Firefox & Chrome Web Extension Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: "Create a release"
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Get Version"
        run: echo "VERSION=$(jq -r '.version' manifest.json)" >> $GITHUB_ENV

      - name: "Echo Version"
        run: echo $VERSION

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: skribbltypo-release-${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: Stable release of skribbl typo, version ${{ env.VERSION }}
          draft: false
          prerelease: false

  publish-chrome:
    needs: release
    name: "Release Chrome Web Ext"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: "Get Version"
        run: echo "VERSION=$(jq -r '.version' manifest.json)" >> $GITHUB_ENV

      - name: "Echo Version"
        run: echo $VERSION

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: typo-chrome-release-${{ env.VERSION }}.zip
          exclusions: "*.git* *.xpi skribbltypo.user.js userscript-gen.js readme.md patch.json /*extensions/* *.web-extension-id .editorconfig .github/"

      - name: Append to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: typo-chrome-release-${{ env.VERSION }}
          path: typo-chrome-release-${{ env.VERSION }}.zip

      - name: Append to release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: typo-chrome-release-${{ env.VERSION }}.zip
          asset_name: typo-chrome-release-${{ env.VERSION }}.zip
          asset_content_type: application/zip
