name: Firefox Web Extension Release
on:
  push:
    branches:
      - master
jobs:
  build-firefox:
    name: "Build and sign Firefox Web Ext"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: "Get Version"
        run: echo "VERSION=$(jq -r '.version' manifest.json)" >> $GITHUB_ENV

      - name: "Echo Version"
        run: echo $VERSION

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: ./
          exclusions: '["skribbltypo.user.js", "userscript-gen.js"," patch.json", "/*extensions/*"]'

      - name: "web-ext sign"
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          channel: unlisted
          apiKey: ${{ secrets.MOZILLA_API_KEY }}
          apiSecret: ${{ secrets.MOZILLA_API_SECRET }}
          timeout: 900000

      - name: Archive signed XPI
        uses: actions/upload-artifact@v2
        with:
          name: typo-firefox-signed-${{env.VERSION}}.xpi
          path: ${{ steps.web-ext-sign.outputs.target }}
