name: Create Archive
on: [push]
jobs:
  build:  
    env:
        RELEASE: typo-release-beta22.9.1.zip
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: env.RELEASE
        exclusions: '*.git* *.xpi changelog.md *.web-extension-id .editorconfig .github/'  
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: env.RELEASE
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: env.RELEASE
