name: Create Archive
on: 
  [push]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: release.zip
        exclusions: '*.git* *.xpi changelog.md *.web-extension-id .editorconfig .github/'  
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: 'release.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: 'store-release-24.1.3'

  userscript-build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Userscript Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
    - uses: actions/checkout@v3

    # Build steps
    - uses: actions/setup-node@v3
      with:
        node-version: '12' 
    - name: Generate userscript
      run: node userscript-gen.js

    # Commit and push all changed files.
    - name: GIT Commit Build Artifacts (coverage, dist, devdist, docs)
      # Only run on main branch push (e.g. after pull request merge).
      if: github.event_name == 'push'
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "toobeeh@users.noreply.github.com"
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
