name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@oldSkribbl
    - name: Archive Release
      uses: thedoctor0/zip-release@oldSkribbl
      with:
        filename: 'typo-release-store22.4.0.zip'
        exclusions: '*.git* *.xpi changelog.md *.web-extension-id .editorconfig .github/'  
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "typo-release-store22.4.0.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: "typo-release-store22.4.0"
